### ISSUE TITLE
Additional column groups besides required and recommended?

### ISSUE THREAD

**Issue by turbomam** [Public-Health-Bioinformatics/covid19ValidationGrid#210]
Could DataHarmonizer support additional column groups?

One application I'm thinking of is support for all of the various MIxS packages in one template. I think there are 10 or 15 now. Maybe that's too many. Maybe I should just create a separate DataHarmonizer template for each package, because they could require different validation rules.

**Comment by ddooley** [comment]
I think this is resolved now insofar as both Marks branch https://turbomam.github.io/DataHarmonizer/main.html and the latest DH linkml-datastructure branch show multiple MIxS templates generated from a single linkml set of MIxS files, with lots of field sections visible in them.  Ok to close this?

**Comment by turbomam** [comment]
I think the section jumping plus the multiple-template menu from linkml-datastructure meet our needs in NMDC. Thanks.
