### ISSUE TITLE
regular expression validator?

### ISSUE THREAD

**Issue by turbomam** [Public-Health-Bioinformatics/covid19ValidationGrid#213]
I haven't checked carefully yet. Is there a regular expression validator, for something like identifiers or hand-entered ontology IDs?

**Comment by ddooley** [comment]
Data Harmonizer doesn't have a RE string option for validating text or other literals.  But it can be useful we know - esp if certain fields specify accession ids that are in a particular format.

**Comment by turbomam** [comment]
Thanks @ddooley 

@dehays I'm going to touch base with you before adding anything else to this issue. Thanks for your input.
