### ISSUE TITLE
CanCOGeN template: LIMS export will now use DH values, null values special coding should be removed

### ISSUE THREAD

**Issue by griffie** [Public-Health-Bioinformatics/covid19ValidationGrid#226]
The NML LIMS export will now use all the original DH values (the capitalized fields are still needed but I removed all the NML values from the CanCOGeN template).

This includes the null values, which previously were all caps etc and required special coding.
Because the DH should now just export whatever values are input, including the null values, the special coding for null values should be removed.

**Comment by ddooley** [comment]
Ok, this vocab is updated and now in master.
