### ISSUE TITLE
Imported csv date validation prbolems.

### ISSUE THREAD

**Issue by cmrn-rhi** [Public-Health-Bioinformatics/covid19ValidationGrid#27]
Dates imported in the appropriate ISO 8601 standards are being flagged as invalid and sometimes reformatted into an invalid format and/or a different date upon upload.

EXAMPLES:
- **"2020"** (YYYY valid format) is being flagged **invalid**.
- **"2020-04"** (YYYY-MM valid format) converted to **"3/31/20"** upon import.
- **"2020-01"** (YYYY-MM valid format) converted to **"12/31/19"** upon import.
- **4/4/2020"" (invalid format) converted to **"4/4/20"**.
- **"2019-12-20"** (YYYY-MM-DD valid format) converted to **"12/19/19"** upon import.

**Comment by ivansg44** [comment]
> "2020" (YYYY valid format) is being flagged invalid.

I thought `'2020'` was supposed to be invalid. @griffie Can you clear this up?

>- "2020" (YYYY valid format) is being flagged invalid.
>- "2020-04" (YYYY-MM valid format) converted to "3/31/20" upon import.
>- "2020-01" (YYYY-MM valid format) converted to "12/31/19" upon import.
>- **4/4/2020"" (invalid format) converted to "4/4/20".
>- "2019-12-20" (YYYY-MM-DD valid format) converted to "12/19/19" upon import.

I reproduced all these. Need to investigate what the date editor is doing.

**Comment by griffie** [comment]
2020 should not be considered valid because it's not granular enough. We at least need a month. Actually, we need a day, or else the data will be rejected by GISAID. But as to the issue at hand, "2020" is too vague and needs to be corrected. Is the reason for an invalid entry being provided to the user?

**Comment by ivansg44** [comment]
Nope. It just gets invalidated. Perhaps a grayed out placeholder in such cells that says DD-MM-YYYY would suffice as explanation. Or even adding it to the column label in brackets (DD-MM-YYYY).

Otherwise, they can always double click the header to see the acceptable format.

**Comment by ivansg44** [comment]
Ah, in the guidance it currently says:

> ISO 8601 standard "YYYY-MM-DD", "YYYY-MM" or "YYYY".

**Comment by griffie** [comment]
You're right. Strictly speaking, that is what the ISO standard allows. We should change the guidance! My bad, my bad... I'll change the text, but can we force a YYYY-MM-DD?

**Comment by ivansg44** [comment]
Yes, definitely. I believe we're enforcing it right now. There's just some bugs on import mentioned in OP.
