### ISSUE TITLE
Valid imported numbers flagged invalid

### ISSUE THREAD

**Issue by cmrn-rhi** [Public-Health-Bioinformatics/covid19ValidationGrid#28]
All imported passage numbers (from a csv file) were displayed as invalid. If I entered the cell, did not change any values in it and then validated, the numbers were considered valid.

The same thing happened for Number Base Pairs, Consensus Genome Length, Mean Contig Length, and N50.

Ns per 100 kbp immediately recognized all values (int and float) as valid, and recognized non-numerals as invalid (as it should).

**Comment by ivansg44** [comment]
I was able to reproduce this. Seems like something's iffy with integer validation.
