### ISSUE TITLE
data loss when importing with 1st row column headers

### ISSUE THREAD

**Issue by cmrn-rhi** [Public-Health-Bioinformatics/covid19ValidationGrid#41]
If the user imports a file where the headers are on the first row, and they declare so on the prompt (‘Which row in your file has the column headers?’ ‘1’) then the second row of the document (first row of data) is truncated (i.e. the row is gone, an empty row does not remain in place). This happens for all three file types (csv, tsv, xlsx).

**Comment by ivansg44** [comment]
Seems to be a problem with `mapMatrixToGrid`.
