### ISSUE TITLE
Date validation showing YYYY-MM imports as invalid

### ISSUE THREAD

**Issue by cmrn-rhi** [Public-Health-Bioinformatics/covid19ValidationGrid#44]
All dates imported with the YYYY-MM format were designated invalid when they should be valid. Occurred for all three file types (csv, tsv, xlsx). 

Dates Tested: 2019-12, 2020-05, 2020-03, 2020-01, 2020-04.

**Comment by ivansg44** [comment]
I believe we are only accepting YYYY-MM-DD now.

**Comment by cmrn-rhi** [comment]
Understood. The guidance field information on the validator (0.4.2) still states "YYYY-MM" and "YYYY" for the date field headers.

**Comment by ivansg44** [comment]
I need to publish a new release. We have an updated reference guide on our master branch.
