### ISSUE TITLE
Body product term listed under anatomical material

### ISSUE THREAD

**Issue by cmrn-rhi** [Public-Health-Bioinformatics/covid19ValidationGrid#50]
Body product "Fluid (seminal)" is being labelled invalid. Appears to still be listed under "anatomical material" rather than "body product" in `data.js`. Is correctly listed under body product in `data.tsv`.

**Comment by ivansg44** [comment]
@griffie @cmrn-rhi Is `"Fluid (seminal)"` supposed to be under `body product`? I noticed all the other fluids are under `anatomical material`.

**Comment by griffie** [comment]
"Body product" is a material that's meant to be secreted/excreted from the body. So whereas blood and saliva have jobs inside the body, feces, semen, urine, sweat, are meant to go out. So seminal fluid is categorized as a body product. Make sense?

**Comment by ivansg44** [comment]
Makes sense. Have you considered renaming `"Fluid (seminal)"` to just `"semen"`, so that it matches the pattern used for the rest of `body product`'s vocabulary (e.g., `"urine"`, `"sweat"` and `"breast milk"`)?

**Comment by griffie** [comment]
Let me have a quick chat with Rhiannon. Not sure if she structured that to match the other fluids when seminal fluid was under anatomical material before (and I subsequently moved it), or whether that was from an ontology. Will let you know shortly....

**Comment by cmrn-rhi** [comment]
There's no issue with renaming it. It was just structured that way to fit
in with the other fluids when it was grouped with them.
